version: "3.9"

services:
  frontend:
    container_name: react-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173" # Vite default
    volumes:
      - .:/app # Sync source code
      - /app/node_modules # Prevent node_modules override by host
    environment:
      - NODE_ENV=development
    command: ["pnpm", "dev"]
