services:
  frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: "https://mail-service-production-91f5.up.railway.app/api/v1"
    ports:
      - "8080:80" # host:container -> access app via http://localhost:8080
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # volumes:                       # Optional: Enable for hot reload in dev
    #   - .:/app
    #   - /app/node_modules
